/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2ecb4c23-ea87-4159-8124-43f47d9b49ea",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3T5YZJbxB",
    "aws_user_pools_web_client_id": "726gfishud3cjieiutcks3n85d",
    "oauth": {}
};


export default awsmobile;
