/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:78bbbadf-ba8e-42c9-9822-99225b2f396a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8DrfhrY5n",
    "aws_user_pools_web_client_id": "2vhuoe0n09i6sh70fn86bgdnqm",
    "oauth": {}
};


export default awsmobile;
